# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}: {
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = ["xhci_pci" "ahci" "nvme" "usbhid" "usb_storage" "sd_mod"];
  boot.initrd.kernelModules = ["amdgpu" "uinput"];
  boot.kernelModules = ["kvm-amd" "uinput"];
  boot.supportedFilesystems = ["ntfs"];

  fileSystems."/mnt/games/ssd" = {
    device = "/dev/disk/by-label/GAMESSSD";
    fsType = "ext4";
    options = [
      "nofail"
      "exec"
      "users"
    ];
  };

  environment.systemPackages = [pkgs.rclone];
  environment.etc."rclone-beryllium.conf".text = ''
    [beryllium]
    type = sftp
    host = 10.3.0.1
    port = 7319
    user = christopher
    key_file = /home/christopher/.ssh/id_ethnuc
  '';

  fileSystems."/mnt/beryllium" = {
    device = "beryllium:/var/sftp";
    fsType = "rclone";
    options = [
      "nofail"
      "nodev"
      "allow_other"
      "args2env"
      "config=/etc/rclone-beryllium.conf"
    ];
  };

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.eno1.useDHCP = lib.mkDefault true;

  powerManagement.cpuFreqGovernor = lib.mkDefault "performance";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
